### ISSUE TITLE
pypy newbytes != cpython newbytes

### ISSUE THREAD

**Issue by mmattice** [PythonCharmers/python-future#260]
It looks like pypy is the odd interpreter out. 

Python 2.7.3 (2.2.1+dfsg-1ubuntu0.3, Sep 30 2015, 15:18:40)
[PyPy 2.2.1 with GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``PyPy 2.0 released''
>>>> import future
>>>> future.__version__
'0.15.2'
>>>> from future.types import newbytes
>>>> list(newbytes('\x01\x01'))
['\x01', '\x01']
>>>> 

Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import future
>>> future.__version__
'0.15.2'
>>> from future.types import newbytes
>>> list(newbytes('\x01\x01'))
[1, 1]
>>> 

Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list(b'\x01\x01')
[1, 1]
>>>

**Comment by Samureus** [comment]
PyPy 2.2.1 is too old, apart from the module attribute error, it seems to work fine with 5.6

```python
$ python
Python 2.7.12 (aff251e543859ce4508159dd9f1a82a2f553de00, Nov 12 2016, 08:50:18)
[PyPy 5.6.0 with GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``if you want it to be virtual, you
should not force it''
>>>> import future
>>>> future.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
>>>> dir(future)
['__author__', '__builtins__', '__copyright__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__title__', '__ver_major__', '__ver_minor__', '__ver_patch__', '__ver_sub__', '__version__']
>>>> future.__version__
'0.16.0'
>>>> from future.types import newbytes
>>>> list(newbytes('\x01\x01'))
[1, 1]
```

**Comment by mmattice** [comment]
That's super interesting.   Seems the "fix" for me is to require sudo on travis-ci.  Thanks.
